stages:
  - build
  - deploy-gh
build debian:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: "overlay"
  before_script:
    - docker version
    - docker info
  script:
    - docker build -f ./tests/debian-8.Dockerfile .
    - docker build -f ./tests/debian-9.Dockerfile .
    - docker build -f ./tests/debian-10.Dockerfile .
build ubuntu:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: "overlay"
  before_script:
    - docker version
    - docker info
  script:
    - docker build -f ./tests/ubuntu-16.04.Dockerfile .
    - docker build -f ./tests/ubuntu-18.04.Dockerfile .
    - docker build -f ./tests/ubuntu-19.04.Dockerfile .
  after_script:
    - docker image prune -af
deploy to github:
  stage: deploy-gh
  only:
   - master
  script:
    - ls -la
    - chmod +x ./git-push
    - ./git-push git@github.com:goodservers/docker-server.git